### ISSUE TITLE
Merging the docker stuff

### ISSUE THREAD

**Issue by bochecha** [Cangjians/build-essential#1]
Hi @yookoala 

I can't believe it took me so long to finally have a serious look at merging all your work with Docker for our CI. Seriously, I've done a terrible job at this, my sincere apologies for that. 😞 

In any case, I'm looking at it right now, hoping to merge it all real soon. I'm starting with this repository for obvious reasons, and I've got a few questions.

1. What is the `Dockerfile` symlink for? Does something really need a default here? Or can we remove it, so we don't give the impression that one OS is better supported than others?

2. It seems that all the build-essential images get rebuild automatically by the Docker Hub every time we push to this repository, can you confirm I got this right?

3. Can we set it up so that the images get rebuilt when the base images (i.e the ones used as `FROM`, for example `fedora:25`) are changed?

4. I'm not sure how openSUSE Leap works, in terms of their release cycle, and I see you haven't used it anyway for the libcangjie CI, so maybe we should just remove that image? (also, neither of us uses openSUSE, I use Fedora and IIRC you use Ubuntu, so maybe we should just focus on those 2 at first)

5. I'm not sure what those `latest` and `latest-fedora` tags are, can we remove them?

All in all, you've done a great job with all this, let me apologize once more for not looking into it in a reasonable amount of time.

Once you've answered those questions above and I understand better this build-essential repo, I'll proceed with your work on the libcangjie CI. I'll also probably replace the fedora:25 and ubuntu:16.04 images by ones based on the latest versions of their respective OS.

**Comment by yookoala** [comment]
1. The symlink is a simple way to set the default docker image file. It should be pointing to the latest Ubuntu that we want to support (e.g. latest LTS or simply latest). Suppose we will create multiple `Dockerfile.*` files and the `latest` symlink will always point to the one to build the image tagged as `latest`. (as opposed to us setting the Dockerhub every time for distro upgrade).

2. The images got rebuilt either (a) we push to the repository; or (b) the depending docker image updated. The settings in docker hub ensures (b) to happen.

3. As mentioned in 2, Dockerhub support that in their settings backend.

4. That image was a response to a previously reported issue (Cangjians/pycangjie#32). I wanted to make sure that we can test it. Probably not a sufficient setup (:-P). I suppose we can improve it to make it a part of regular test (or discard it).

5. `latest` is traditionally tagging the image to use by default in docker for a given repo. I believe it is a standard enforced by docker ecosystem. `latest-fedora` or `latest-*` is a de facto standard in most docker library for "the latest build in the repo with different feature than the default `latest`".

**Comment by bochecha** [comment]
For 2 and 3, you rock!

About 4, since neither you nor I know much about openSUSE, and since it isn't plugged to the libcangjie/pycangjie/ibus-cangjie CI, I suggest we remove it for now, and reintroduce it eventually at a later date if we actually start using it. 😃 

As for the `latest`, in other projects I've seen that it was a convention, but it's not mandatory. (e.g in Ideascube we don't have it at all and everything is just fine)

Since we don't actually provide images for public consumption, and aren't in the business of recommending one distro over another, I'd rather we just don't have it.

Thanks for answering faster than I did. I'll work on this and merge it all ASAP.

My current plan is to test (and thus have images for) the following operating systems:

* the next Ubuntu
* the latest Ubuntu
* the latest Ubuntu LTS
* the next Fedora
* the latest Fedora

**Comment by bochecha** [comment]
One more question: what's this for?

```
# mark the version of this image
RUN echo "ubuntu-lts" > /var/version
```

**Comment by yookoala** [comment]
If I remember it correctly, this is for distro detections for the CI testing process.

**Comment by bochecha** [comment]
> If I remember it correctly

Yeah, I'm aware you might have forgotten this, given how long ago you made it. >_<

You seem to be using it:

* [in the libcangjie Docker file](https://github.com/Cangjians/libcangjie/pull/99/files#diff-3254677a7917c6c01f55212f86c57fbfR11) to print to the console what OS is being used;
* [in the pycangjie CI](https://github.com/Cangjians/pycangjie/pull/31/files#diff-354f30a63fb0907d4ad57269548329e3R34) to print to the console what OS is being used;
* [in the ibus-cangjie CI](https://github.com/Cangjians/ibus-cangjie/pull/79/files#diff-354f30a63fb0907d4ad57269548329e3R45) to print to the console what OS is being used;

I'm not sure that's very useful though. When the tests will be running, Travis will show us what environment it has run the tests in, and as a result we will know the OS being used without needing to print it to the console.

Am I missing something and it might be used elsewhere? If not, I'd rather just remove it.

**Comment by yookoala** [comment]
The environment variables of Travis CI doesn't pass into Docker environment. Thus need a way for the build-essential image to tell its user what distro it is.

**Comment by bochecha** [comment]
> a way for the build-essential image to tell its user what distro it is.

But why would we need that? The tests don't seem to require this at all.

**Comment by yookoala** [comment]
The print out is to re-ensure that the test is running on a correct distro image. There were some mistake in my previous attempt when all the supposed different OS test were actually ran in Ubuntu image. This is a precaution measure against similar problem to arise in the future (sort of regression detection).

**Comment by bochecha** [comment]
Ok, that 's a very valid use-case, I hadn't thought about that. :+1:
